TouristPlaceFluentApi/TouristPlaceFluentApi/Models/TouristPlace.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace TouristPlaceFluentApi.Models
{
    public class TouristPlace
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }

        public string ImageUrl { get; set; }

        [Required]
        public int Rating { get; set; }

        [Required]
        public string Address { get; set; }
        [Display(Name = "Type")]
        public int TypeId { get; set; }
        public virtual PlaceType Type { get; set; }
    }
}

TouristPlaceFluentApi/TouristPlaceFluentApi/Controllers/TouristPlacesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TouristPlaceFluentApi.Data;
using TouristPlaceFluentApi.Models;

namespace TouristPlaceFluentApi.Controllers
{
    [Authorize]
    public class TouristPlacesController : Controller
    {
        private readonly TouristPlaceContext _context;
        private readonly IWebHostEnvironment _hostingEnvironment;
        public TouristPlacesController(TouristPlaceContext context, IWebHostEnvironment HostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = HostingEnvironment;
        }

        public async Task<IActionResult> Index(string SearchValue, Boolean? IsAscending)
        {
            if (SearchValue == null)
            {
                SearchValue = "";
                HttpContext.Session.SetString("searchValue", SearchValue);
            }
            else
            {
                HttpContext.Session.SetString("searchValue", SearchValue);
            }

            if (IsAscending != null)
            {
                IsAscending = !IsAscending;
                HttpContext.Session.SetString("sort", IsAscending.ToString());
            }
            else if (IsAscending == null && HttpContext.Session.GetInt32("sort") != null)
            {
                IsAscending = Convert.ToBoolean(HttpContext.Session.GetString("sort"));
            }
            else
            {
                IsAscending = false;
                HttpContext.Session.SetString("sort", IsAscending.ToString());
            }

            ViewData["sortValue"] = IsAscending;
            ViewData["searchValue"] = SearchValue;

            if (IsAscending.Value)
            {
                return View("Index", await _context.TouristPlaces.Where(m => m.Name.Contains(SearchValue)).OrderByDescending(m => m.Rating).ToListAsync());
            }
            else
            {
                return View("Index", await _context.TouristPlaces.Where(m => m.Name.Contains(SearchValue)).OrderBy(m => m.Rating).ToListAsync());
            }
            //Without Lazy Loading
            /*
             if (IsAscending.Value)
            {
                return View("Index", await _context.TouristPlaces.Where(m => m.Name.Contains(SearchValue)).Include(m=>m.Type).OrderByDescending(m => m.Rating).ToListAsync());
            }
            else
            {
                return View("Index", await _context.TouristPlaces.Where(m => m.Name.Contains(SearchValue)).Include(m=>m.Type).OrderBy(m => m.Rating).ToListAsync());
            }
             */
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var touristPlace = await _context.TouristPlaces
                .FirstOrDefaultAsync(m => m.Id == id);
            //Without Lazy Loading
            /*var touristPlace = await _context.TouristPlaces.Include(m=>m.Type)
                .FirstOrDefaultAsync(m => m.Id == id);*/
            if (touristPlace == null)
            {
                return NotFound();
            }

            return View(touristPlace);
        }

        public IActionResult Create()
        {
            ViewBag.Types = _context.PlaceTypes.ToList();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile Image, [Bind("Id, Name, Image, Rating, Address, TypeId")] TouristPlace touristPlace)
        {
            if (ModelState.IsValid)
            {
                if (Image == null)
                    return View(touristPlace);
                touristPlace.ImageUrl = SaveImageReturnUniqueName(Image);
                _context.Add(touristPlace);

                await _context.SaveChangesAsync();
                return RedirectToAction("Index", new { searchValue = HttpContext.Session.GetString("searchValue") });
            }
            return View(touristPlace);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var touristPlace = await _context.TouristPlaces
                .FirstOrDefaultAsync(m => m.Id == id);
            //Without Lazy Loading
            /*var touristPlace = await _context.TouristPlaces.Include(m=>m.Type)
                .FirstOrDefaultAsync(m => m.Id == id);*/
            if (touristPlace == null)
            {
                return NotFound();
            }
            ViewBag.Types = _context.PlaceTypes.Where(m => m.Id != touristPlace.TypeId).ToList();
            return View(touristPlace);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, IFormFile Image, [Bind("Id, Name, Rating, Address, TypeId")] TouristPlace touristPlace)
        {
            if (id != touristPlace.Id)
            {
                return NotFound();
            }

            var touristPlaceItem = _context.TouristPlaces.Find(id);

            if (ModelState.IsValid)
            {
                try
                {

                    if (Image != null)
                    {
                        touristPlaceItem.ImageUrl = SaveImageReturnUniqueName(Image);

                    }
                    touristPlaceItem.Name = touristPlace.Name;
                    touristPlaceItem.Rating = touristPlace.Rating;
                    touristPlaceItem.Address = touristPlace.Address;
                    touristPlaceItem.TypeId = touristPlace.TypeId;
                    _context.Update(touristPlaceItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TouristPlaceExists(touristPlace.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index", new { searchValue = HttpContext.Session.GetString("searchValue") });

            }
            return View(touristPlace);

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var touristPlace = await _context.TouristPlaces
                .FirstOrDefaultAsync(m => m.Id == id);

            //Without Lazy Loading
            /*var touristPlace = await _context.TouristPlaces.Include(m=>m.Type)
                .FirstOrDefaultAsync(m => m.Id == id);*/
            if (touristPlace == null)
            {
                return NotFound();
            }

            return View(touristPlace);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var touristPlace = await _context.TouristPlaces.FindAsync(id);
            _context.TouristPlaces.Remove(touristPlace);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index", new { searchValue = HttpContext.Session.GetString("searchValue") });
        }

        private bool TouristPlaceExists(int id)
        {
            return _context.TouristPlaces.Any(e => e.Id == id);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("UserLogin", "Login");
        }

        public string SaveImageReturnUniqueName(IFormFile Image)
        {
            var uploadFolder = Path.Combine(_hostingEnvironment.WebRootPath, "images");
            string uniqueName = Guid.NewGuid().ToString() + "_" + Image.FileName;
            string fileUrl = Path.Combine(uploadFolder, uniqueName);
            Image.CopyTo(new FileStream(fileUrl, FileMode.Create));
            return uniqueName;
        }
    }
}

TouristPlaceFluentApi/TouristPlaceFluentApi/Views/TouristPlaces/Create.cshtml
@model TouristPlaceFluentApi.Models.TouristPlace
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

@{
    ViewData["Title"] = "Create";

}


<h1>Create</h1>

<h4>TouristPlace</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Image">Image</label>
                <input id="Image" name="Image" type="file" class="form-control align-middle" />
                <span><img id="imagePreview" src="" style="" /></span>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" type="number" max="5" min="1" value="1" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" class="form-control">
                    @foreach (PlaceType item in ViewBag.Types)
                    {
                        <option value=@item.Id>@item.Name</option>
                    }

                </select>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-searchValue="@httpContextAccessor.HttpContext.Session.GetString("searchValue")">Back to List</a>
</div>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            $('#Image').change(function () {
                $('#imagePreview').css("display", "block");
                const file = $('#Image')[0].files[0];
                const reader = new FileReader();
                var previewImg = $('#imagePreview');
                reader.addEventListener("load", function () {
                    previewImg.attr("src", reader.result);
                    imgC = reader.result;
                }, false);

                if (file) {
                    reader.readAsDataURL(file);
                }
            });
        });
    </script>
}

TouristPlaceFluentApi/TouristPlaceFluentApi/Views/TouristPlaces/Delete.cshtml
@model TouristPlaceFluentApi.Models.TouristPlace
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TouristPlace</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Image
        </dt>
        <dd class="col-sm-10">
            <img src="~/images/@Model.ImageUrl" style="height:100px;width:100px;" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TypeId)
        </dt>
        <dd class="col-sm-10">
            @Model.Type.Name
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-searchValue="@httpContextAccessor.HttpContext.Session.GetString("searchValue")">Back to List</a>
    </form>
</div>

TouristPlaceFluentApi/TouristPlaceFluentApi/Views/TouristPlaces/Details.cshtml
@model TouristPlaceFluentApi.Models.TouristPlace
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

@{
    ViewData["Title"] = "Details";
}


<h1>Details</h1>

<div>
    <h4>TouristPlace</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            Image
        </dt>
        <dd class="col-sm-10">
            <img src="~/images/@Model.ImageUrl" style="height:100px;width:100px;" />
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TypeId)
        </dt>
        <dd class="col-sm-10">
            @Model.Type.Name
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)

        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index" asp-route-searchValue="@httpContextAccessor.HttpContext.Session.GetString("searchValue")">Back to List</a>
</div>

TouristPlaceFluentApi/TouristPlaceFluentApi/Views/TouristPlaces/Edit.cshtml
@model TouristPlaceFluentApi.Models.TouristPlace
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

@{
    ViewData["Title"] = "Edit";

}

<h1>Edit</h1>

<h4>TouristPlace</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Image">Image</label>
                <input id="Image" name="Image" type="file" class="form-control" />
                <span><img id="imagePreview" src="~/images/@Model.ImageUrl" style="height:100px;width:100px;" /></span>
                <span asp-validation-for="ImageUrl" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TypeId" class="control-label"></label>
                <select asp-for="TypeId" class="form-control">
                    <option value=@Model.Type.Id>@Model.Type.Name</option>
                    @foreach (PlaceType Item in ViewBag.Types)
                    {
                        <option value=@Item.Id>@Item.Name</option>
                    }

                </select>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-route-searchValue="@httpContextAccessor.HttpContext.Session.GetString("searchValue")">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
        $(document).ready(function () {
            var imagePreveiw = $('#imagePreview');
            if (imagePreveiw.css("display") == "none")
                imagePreveiw.css("display", "block");
            $('#Image').change(function () {
                const file = $('#Image')[0].files[0];
                const reader = new FileReader();
                var previewImg = $('#imagePreview');
                reader.addEventListener("load", function () {
                    // convert image file to base64 string
                    previewImg.attr("src", reader.result);
                    imgC = reader.result;
                }, false);

                if (file) {
                    reader.readAsDataURL(file);
                }
            });
        });
    </script>
}

TouristPlaceFluentApi/TouristPlaceFluentApi/Views/TouristPlaces/Index.cshtml
@model IEnumerable<TouristPlaceFluentApi.Models.TouristPlace>
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor httpContextAccessor

@{
    ViewData["Title"] = "Index";
}

@section css{
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
}

<h1>Index</h1>
<p>
    <a asp-action="Create">Create New</a>
</p>

<form method="post" asp-action="Index">

    <div class="input-group">
        <input type="text" id="SearchValue" name="SearchValue" placeholder="Search term..." class="form-control" value="@ViewData["searchValue"]" />
        <input type="hidden" id="Search" name="Search" placeholder="Search term..." class="form-control" value="Search" />
        <span class="input-group-btn">
            <button class="btn btn-default" type="submit"><span class="glyphicon glyphicon-search"></span></button>
        </span>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Image
            </th>
            <th>
                Type
            </th>
            <th>
                <a asp-controller="TouristPlaces" asp-action="Index" asp-route-searchValue="@httpContextAccessor.HttpContext.Session.GetString("searchValue")"
                   asp-route-IsAscending="@ViewData["sortValue"]">@Html.DisplayNameFor(model => model.Rating)</a>

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <img src="~/images/@Html.DisplayFor(modelItem => item.ImageUrl)" style="height:100px;width:100px;" />
                </td>
                <td>
                    @item.Type.Name
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>